### ISSUE TITLE
libjpeg.a version

### ISSUE THREAD

**Issue by amedoc** [LeiWang1999/ZYNQ-NVDLA#22]
Hi, 
I have a question about the libjpeg.a library. Did you use the prebuilt one from the nvdla/sw repository or you have built a different one because the library sizes are different?
Many thanks in advance.

**Comment by LeiWang1999** [comment]
@amedoc 
You can use the prebuilt one provided by the official nvdia/sw repo if your target arch is aarch64, for zynq mpsoc with arm64 processor I worked fine with the prebuilt one, but if you wanna deploy nvdla align with an arm32 processor, you need to rebuilt a new one because the prebuilt one was compiled based on a 64bit processor .

**Comment by LeiWang1999** [comment]
close as it has been resloved.
